name: Java CI

on: 
  pull_request:
    branches-ignore: 'gh-pages'
  push:
    branches-ignore: 'gh-pages'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build -PbinariesOnly
    - name: Rename app artifact
      run: mv app/build/libs/level-manipulator-app-*-app.jar app/build/libs/level-manipulator-app.jar
    - name: Archive app artifact
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: Level-Manipulator
        path: app/build/libs/level-manipulator-app.jar
